name: Truffle Tests

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test:
    # Name the Job
    name: Truffle Tests - Layer 1 and Layer 2
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g truffle
          npm install -g ganache-cli

      - name: Start Ganache for Layer 1
        run: ganache-cli --gasLimit=0x1fffffffffffff &
        # Backgrounding ganache-cli like this should not cause timing issues, and
        # is recommended by https://soliditydeveloper.com/continuous-integration
        # For the error "Something went wrong while attempting to connect to the
        # network", implicate this line that starts up ganache.
      
      - name: Run Core Protocol Tests
        run: npm run test:protocol
      
      - name: OVM Compilation
        run: npm run compile:ovm
      

# Opens a shell on the runner. Useful for debugging actions.
#- name: Setup tmate session
#  uses: mxschmitt/action-tmate@v3
